import React from "react";
import WeatherInformation from "../components/WeatherInformation";
import WeatherMoreInformation from "../components/WeatherMoreInformation";
import Head from "next/head";
import { useContext } from "react";
import { WeatherContext } from "../contexts/WeatherContext";

const Home = () => {
  const { backgroundImage } = useContext(WeatherContext);
  return (
    <>
      <Head>
        <title>Weather Forecast Website</title>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0'
        />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/weather-app.ico' />
      </Head>

      <div
        className={`flex flex-row items-start justify-between  bg-cover bg-center bg-no-repeat ${backgroundImage}`}>
        <WeatherInformation />
        <WeatherMoreInformation />
      </div>
    </>
  );
};

export default Home;
