import Head from "next/head";
import React from "react";
import WeatherInformation from "../components/WeatherInformation";
import WeatherMoreInformation from "../components/WeatherMoreInformation";
import WeatherContextProvider from "../contexts/WeatherContext";

const Home = () => {
  return (
    <>
      <Head>
        <title>Weather Forecast Website</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/weather-app.ico' />
      </Head>

      <div className='flex flex-row items-start justify-between'>
        <WeatherContextProvider>
          <WeatherInformation />
          <WeatherMoreInformation />
        </WeatherContextProvider>
      </div>
    </>
  );
};

export default Home;
